version: '3.0'

services:
  grafana:
    container_name: 'apricote-hcloud-datasource'
    platform: 'linux/amd64'
    user: 1000:1000
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        # Keep at the lowest supported version of grafana as indicated in plugin.json
        grafana_version: ${GRAFANA_VERSION:-10.0.3}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/apricote-hcloud-datasource
      - ./provisioning:/etc/grafana/provisioning
    environment:
      GF_METRICS_ENABLED: 'true'
